#
#  codeql-analysis.yml
#  Track21

#  Created by Hrishav Sunar on 7/11/2024.

on:
  push:
    branches: [master, trunk]
  pull_request:
    branches: [master]
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      
jobs:
  test:
    runs-on: macos-15

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3
      
    - name: Cache Xcode Derived Data
      uses: actions/cache@v3
      with:
        path: ~/Library/Developer/Xcode/DerivedData
        key: ${{ runner.os }}-xcode-${{ hashFiles('**/*.xcodeproj/**', '**/*.xcworkspace/**', '**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-xcode-
          
    - name: Install xcpretty
      run: sudo gem install xcpretty

    - name: Run Test
      run: xcodebuild test -scheme Track21 -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=18.0' | xcpretty
